config:
  snapshot_identifier                   : "mgmt-2024-04-18-02-10"
  engine                                : "aurora-postgresql"
  multi_az_engine                       : "postgres"
  engine_version                        : "12.12"
  family                                : "postgres12"
  db_cluster_parameter_group_family     : "aurora-postgresql12"
  major_engine_version                  : "12"
  port                                  : 5432
  backup_window                         : "03:00-06:00"
  allow_major_version_upgrade           : true
  auto_minor_version_upgrade            : false
  maintenance_window                    : "sun:00:00-sun:01:00"
  allocated_storage                     : 20 # supported on multi az only
  max_allocated_storage                 : 100 
  multi_az                              : false # 3 subnets are required for multi_az=true
  instance_class                        : "db.r5.large"
  username                              : "postgres_admin"
  backup_retention_period               : 7
  performance_insights_enabled          : true
  performance_insights_retention_period : 7
  autoscaling_min_capacity              : 1
  autoscaling_max_capacity              : 2
  autoscaling_enabled                   : true
  # iops                                : 2500 # supported on multi az only
  iops                                  : null
  storage_type                          : null

#these rules can be modified as required for security purposes

  sg_ingress_rules :
    - from_port    : 5432
      to_port      : 5432
      protocol     : "tcp"
      description  : "Allow Inbound"
      cidr_blocks  : "0.0.0.0/0"
  
  sg_egress_rules :
    - from_port   : 0
      to_port     : 65535
      protocol    : "tcp"
      description : "Allow all egress traffic"
      cidr_blocks : "0.0.0.0/0"
